//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComponentTree.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public long Id { get; set; }
        public Nullable<long> IdParent { get; set; }
        public Nullable<long> IdChild { get; set; }
        public int Quantity { get; set; }
    }
}
